In [ ]:
import numpy as np

In [ ]:
a=[4,6,2,1,5,7]
a.sort()
print(a)

[1, 2, 4, 5, 6, 7]


In [1]:
a=[4,6,2,1,5,7]
print(sorted(a))
#print(b)

[1, 2, 4, 5, 6, 7]


In [ ]:
a=(4,6,2,1,5,7)
b=sorted(a)
print(a)
print(b)

(4, 6, 2, 1, 5, 7)
[1, 2, 4, 5, 6, 7]


In [ ]:
import numpy as np

In [ ]:
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
A1=np.linspace(14,15,16)
print(A1)
A1=np.linspace(14,15,16).reshape(8,2)
print(A1)
A1=np.linspace(14,15,16).reshape(4,4)
print(A1)

[14.         14.06666667 14.13333333 14.2        14.26666667 14.33333333
 14.4        14.46666667 14.53333333 14.6        14.66666667 14.73333333
 14.8        14.86666667 14.93333333 15.        ]
[[14.         14.06666667]
 [14.13333333 14.2       ]
 [14.26666667 14.33333333]
 [14.4        14.46666667]
 [14.53333333 14.6       ]
 [14.66666667 14.73333333]
 [14.8        14.86666667]
 [14.93333333 15.        ]]
[[14.         14.06666667 14.13333333 14.2       ]
 [14.26666667 14.33333333 14.4        14.46666667]
 [14.53333333 14.6        14.66666667 14.73333333]
 [14.8        14.86666667 14.93333333 15.        ]]


In [ ]:
B=np.array([45,56,21,1,90,34]).reshape(2,1,3) #reshape - changes needs saving in another variable
print(B)

[[[45 56 21]]

 [[ 1 90 34]]]


In [ ]:
C=np.array([45,56,21,1,90,34])
C.resize(2,1,3) #changes the shape of original array
print(C)

[[[45 56 21]]

 [[ 1 90 34]]]


In [ ]:
A1=np.array([34,56,78,90])
B1=np.array([7,9,3,12])
C1=A1-B1  #list will through an error while array iterate themselves and perform subtraction
print(C1)

[27 47 75 78]


In [ ]:
A1=np.array([34,56,78,90])
B1=np.array([7,9,3,12])
C1=A1+B1  #list will through an error while array iterate themselves and perform addition
print(C1)

[ 41  65  81 102]


In [ ]:
A1=np.array([34,56,78,90]).reshape(2,2)
B1=np.array([7,9,3,12]).reshape(2,2)
print(A1)
print("********")
print(B1)
print("********")
C=A1*B1  #one on one multiplication
print(C)

[[34 56]
 [78 90]]
********
[[ 7  9]
 [ 3 12]]
********
[[ 238  504]
 [ 234 1080]]


In [ ]:
A1=np.array([34,56,78,90]).reshape(2,2)
B1=np.array([7,9,3,12]).reshape(2,2)
print(A1)
print("********")
print(B1)
print("********")
C=A1@B1  #matrix multiplication
print(C)

[[34 56]
 [78 90]]
********
[[ 7  9]
 [ 3 12]]
********
[[ 406  978]
 [ 816 1782]]


In [ ]:
#another way of matrix multiplication
A1=np.array([34,56,78,90]).reshape(2,2)
B1=np.array([7,9,3,12]).reshape(2,2)
print(A1)
print("********")
print(B1)
print("********")
C=A1.dot(B1)#matrix multiplication
print(C)

[[34 56]
 [78 90]]
********
[[ 7  9]
 [ 3 12]]
********
[[ 406  978]
 [ 816 1782]]


In [ ]:
A=np.array([34.2,56.7,78.2,90.9,90.8])
print(A.max())  #max min accepts only integers and float values
print(A.min())

90.9
34.2


In [ ]:
#maximum elements in matrix
A1=np.array([34,56,78,90,23,65,73,89]).reshape(2,4)
print(A1)
print("********")
print(A1.max(axis=0))   #axis 0-column
print("********")
print(A1.max(axis=1))   #axis 1-row

[[34 56 78 90]
 [23 65 73 89]]
********
[34 65 78 90]
********
[90 89]


In [ ]:
#minimum elements in array
A1=np.array([34,56,78,90,23,65,73,89]).reshape(2,4)
print(A1)
print("********")
print(A1.min(axis=0))   #axis 0-column
print("********")
print(A1.min(axis=1))   #axis 1-row

[[34 56 78 90]
 [23 65 73 89]]
********
[23 56 73 89]
********
[34 23]


In [ ]:
#joining arrays
A1=np.array([34,56,78,90]).reshape(2,2)
B1=np.array([7,9,3,12]).reshape(2,2)
print(A1)
print("********")
print(B1)
print("********")
print("After vertically satcking arrays")#np.stack(((A1,B1),axis=0))
print(np.vstack((A1,B1)))

[[34 56]
 [78 90]]
********
[[ 7  9]
 [ 3 12]]
********
After vertically satcking arrays
[[34 56]
 [78 90]
 [ 7  9]
 [ 3 12]]


In [ ]:
#joining arrays
A1=np.array([34,56,78,90]).reshape(2,2)
B1=np.array([7,9,3,12]).reshape(2,2)
print(A1)
print("********")
print(B1)
print("********")
print("After horizontally stacking arrays")#np.stack(((A1,B1),axis=1))
print(np.hstack((A1,B1)))

[[34 56]
 [78 90]]
********
[[ 7  9]
 [ 3 12]]
********
After horizontally stacking arrays
[[34 56  7  9]
 [78 90  3 12]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A)) #no.of rows=no.of groups
#no.of columns in every group=no.of rows every group    i.e. (3,5,2)
#o/p will be [0,0],[1,1],......
            #[index,index]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#Splitting arrays!
A=np.arange(18).reshape(6,3)
print(A)
print("after splitting")
np.split(A,(3))#(A,no.of equal array divisions)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
A=np.arange(18).reshape(6,3)
print(A)
print("after splitting")
np.split(A,(1,3,5))#(A,no.of equal array divisions)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2]]),
 array([[3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#Splitting arrays!
A=np.arange(18).reshape(6,3)
print(A)
print("after splitting")
np.vsplit(A,(1,3,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[0, 1, 2]]),
 array([[3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#Splitting arrays!
#horizontal splitting
A=np.arange(18).reshape(6,3)
print(A)   #result array starts with 0 index
print("after splitting")
np.hsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
#Splitting arrays!
#vertically splitting-columnns splitting
A=np.arange(18).reshape(3,6)
print(A)   #result array starts with 0 index
print("after splitting")
np.hsplit(A,(1,4))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting


[array([[ 0],
        [ 6],
        [12]]),
 array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [ ]:
A=np.array([23,45,234,76,12]) #single array
print(A)
print(A.argmax())  #returns highest value index position

[ 23  45 234  76  12]
2


In [ ]:
A=np.array([23,45,234,76,12,34,31,178]).reshape(2,4)#index:[0 0 0...]
print(A)                                                  #[1 1 1...]
print(A.argmax(axis=0))                                   #[2 2 2...]

[[ 23  45 234  76]
 [ 12  34  31 178]]
[0 0 0 1]


In [ ]:
A=np.array([23,45,234,76,12,34,31,178]).reshape(2,4)     #index:[0 1 2...]
print(A)                                                       #[0 1 2...]
print(A.argmax(axis=1))                                        #[0 1 2...]

[[ 23  45 234  76]
 [ 12  34  31 178]]
[2 3]


In [ ]:
A=np.array([23,45,234,76,12,34,31,178]).reshape(2,4)
print(A)
print(A.argmin())

[[ 23  45 234  76]
 [ 12  34  31 178]]
4


In [ ]:
A=np.array([23,45,234,76,12,34,31,178]).reshape(2,4)
print(A)
print(A.argmin(axis=1))  #index:[0 1 2...]
                               #[0 1 2...]
                               #[0 1 2...]

[[ 23  45 234  76]
 [ 12  34  31 178]]
[0 0]


In [ ]:
A=np.array([23,45,234,76,12,34,31,178]).reshape(2,4)
print(A)
print(A.argmin(axis=0))  #index:[0 0 0...]
                               #[1 1 1...]
                               #[2 2 2...]

[[ 23  45 234  76]
 [ 12  34  31 178]]
[1 1 1 0]


STATISTICS

In [ ]:
#mean,median,std deviation,variance
A=np.array([12,34,56,78,89])
print("mean:",np.mean(A))
print("median:",np.median(A))
print("Standard variance:",np.std(A))
print("Variance:",np.var(A))

mean: 53.8
median: 56.0
Standard variance: 28.173746644704533
Variance: 793.76


TRIGNOMETRY


In [ ]:
A=np.pi
print(A) #pi value in radians

3.141592653589793


In [ ]:
np.rad2deg(A) #converting pi value in degrees

180.0

In [ ]:
A1=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi/1])
print(A)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
print(np.rad2deg(A1))

[ 45.  60.  90. 180.]


In [ ]:
C=np.array([0,30,45,60,90,120,180])
D=np.deg2rad(C)
print(D)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
print(np.sin(C))
print(np.cos(C))
print(np.tan(C))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118
 -0.80115264]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097
 -0.59846007]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041  0.71312301
  1.33869021]


In [ ]:
np.cos(C)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1) #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1) #cos^-1

0.0

In [ ]:
np.arctan(1) #tan^-1

0.7853981633974483

In [ ]:
a=8
b=6
print(np.hypot(a,b))  #hypotnuese

10.0


SEARCHING AN ARRAY!

In [ ]:
#returns index value
S=np.array([90,3,45,21,34,90,21])
print(np.where(S==45))

(array([2]),)


In [ ]:
S=np.array([90,3,45,21,34,90,21])
print(np.where(S%2==0))  #even numbers index position

(array([0, 4, 5]),)


In [ ]:
S=np.array([90,3,45,21,34,90,21])
print(np.where(S>50))   #greater than 50

(array([0, 5]),)


In [ ]:
X=np.array([12,54,32,11,56,90])
print(np.searchsorted(X,56))   #outputs the index of sorted element

4


LINEAR ALGEBRA AND UFUNC

In [ ]:
AD=np.array([6,24,60,12,18])
SB=np.array([6,14,23,5,45])
print(np.add(AD,SB))
print(np.subtract(AD,SB))
print(np.divide(AD,SB))
print(np.mod(AD,SB))   #r
print(np.divmod(AD,SB))  #q and r

[12 38 83 17 63]
[  0  10  37   7 -27]
[1.         1.71428571 2.60869565 2.4        0.4       ]
[ 0 10 14  2 18]
(array([1, 1, 2, 2, 0]), array([ 0, 10, 14,  2, 18]))


In [ ]:
print(np.diff(AD,SB))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
sorted

<function sorted(iterable, /, *, key=None, reverse=False)>

SET FUNCTIONS

In [ ]:
U=np.array([6,24,60,12,18])
V=np.array([6,4,10,5,4])
print(np.union1d(U,V))

[ 4  5  6 10 12 18 24 60]


In [ ]:
U=np.array([6,24,60,12,18])
V=np.array([6,4,10,5,4])
print(np.setdiff1d(U,V))

[12 18 24 60]


In [ ]:
U=np.array([6,24,60,12,18])
V=np.array([6,4,10,5,4])
print(np.intersect1d(U,V))

[6]


ROUNDING

In [ ]:
a1=np.trunc([-4.134,9.432])
print(a1)

[-4.  9.]


In [ ]:
a2=np.fix([-4.134,9.432])
print(a2)

[-4.  9.]


In [ ]:
a3=np.around([4.134345],3)
print(a3)

[4.134]


In [ ]:
a4=np.floor([-4.134,9.432])
print(a1)

[-4.  9.]


In [ ]:
a5=np.ceil([-4.134,9.432])
print(a5)

[-4. 10.]


In [ ]:
a6=np.array([5,6,82,12,43])
print(np.cumsum(a6))

[  5  11  93 105 148]


In [ ]:
a6=np.array([5,6,82,12,43])
print(np.cumprod(a6))

[      5      30    2460   29520 1269360]


In [ ]:
np.lcm(45,56)


2520

In [ ]:
np.gcd(234,456)

6

In [ ]:
a7=np.array([45,12,34,21])
print(np.lcm.reduce(a7))

21420


In [ ]:
a8=np.array([45,12,34,21])
print(np.gcd.reduce(a8))

1


In [ ]:
a9=np.array([[5,2],[12,4]])          #1/ad-bc(d -b
print(np.linalg.inv(a9))                    # -c a)

[[-1.    0.5 ]
 [ 3.   -1.25]]


RANDOM

In [ ]:
from numpy import random as rd

In [ ]:
R=rd.rand()  #rand(n)  #default limit 0 to 0.99
print(R)

0.446808548701942


In [ ]:
R=rd.rand(10)  #rand(n)  #default limit 0 to 0.99
print(R)

[0.15875081 0.07309951 0.02556397 0.58699067 0.07093556 0.56888166
 0.48633949 0.3281812  0.10129251 0.07511125]


In [ ]:
R=rd.randint(10)  #randint(limit)
print(R)

7


In [ ]:
R=rd.randint(50,size=(2,3))  #randint(limit)
print(R)

[[31 11 38]
 [19 17 45]]


JOINS!

In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])  #1x4+2x5+3x6
print(np.inner(A,B))

32


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])  #1x4+2x5+3x6
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])  #(2x6-5x3) (1x6-3x4)
print(np.cross(A,B))

[-3  6 -3]
