In [ ]:
#variable and string
a=10
print("i am ",a,"years old")

i am  10 years old


a=int(input("enter nuber1"))
b=int(input("enter number2"))
s=int(a+b)
print(s)

In [ ]:
#arthimetic on two  intnumbers
a=int(input("enter number1:"))
b=int(input("enter number2:"))
s=int(a+b)
d=int(a-b)
print("Sum:",s)
print("Difference:",d)
print("multiplicatin:",a*b)
print("remainder2:",a%b)
print("Division:",a/12)
print("power:",a**b)

enter number1:345
enter number2:12
Sum: 357
Difference: 333
multiplicatin: 4140
remainder2: 9
Division: 28.75
power: 2843342266303054544082275390625


In [ ]:
for i in range(0,11):
  print(i)


0
1
2
3
4
5
6
7
8
9
10


In [ ]:
#take a number from a user which is a salary if the salary is more than 50000 there is 10% tax print his final salary
sal=int(input("enter salary"))
if sal>=50000:
  print("the salary after tax is ",(sal-(sal*10)/100));
else:
  print("no tax")

enter salary100000
the salary after tax 90000.0


In [ ]:
#get the salary from user if the salary is more or equal 50000 apply 10% tax deduction if the salry is less than 50000 apply 5% tax if the salary is more than 70000 apply 12% tax if the salart exceeds 1lakh print you are promoted to next level
sal=int(input("enter salary:"))
if sal<=50000:
  print("the salary after  5% tax is ",(sal-(sal*5)/100));
elif sal>=50001 and sal<=70000:
  print("the salary after 10% tax is ",(sal-(sal*10)/100));
elif sal>=71000 and sal<=100000:
  print("the salary after 12% tax is ",(sal-(sal*12)/100));
else:
  print("you are promoted to next level");


enter salary:50100
the salary after 10% tax is  45090.0


In [ ]:
#for loop
ran=range(1,11)
n=int(input("enter number"))
for i in ran:
  print(n, "*",i ,"=",n*i)


enter number14
14 * 1 = 14
14 * 2 = 28
14 * 3 = 42
14 * 4 = 56
14 * 5 = 70
14 * 6 = 84
14 * 7 = 98
14 * 8 = 112
14 * 9 = 126
14 * 10 = 140


In [ ]:
#while loop
n=int(input("enter number:"))
i=1
while i<=10:
  print(n, "*",i ,"=",n*i)
  i=i+1

enter number:19
19 * 1 = 19
19 * 2 = 38
19 * 3 = 57
19 * 4 = 76
19 * 5 = 95
19 * 6 = 114
19 * 7 = 133
19 * 8 = 152
19 * 9 = 171
19 * 10 = 190


In [ ]:
#heterogenous list
list1=[10,'ant',23.5,'K']
for i in list1: #printing elements in a list
  print(i)

10
ant
23.5
K


In [ ]:
#mutable
list1.append("appended")
print(list1)
#inserting
list1.insert(3,"inserted")
print(list1)

[10, 'ant', 23.5, 'K', 'appended', 'appended']
[10, 'ant', 23.5, 'inserted', 'K', 'appended', 'appended']


In [ ]:
l2=[4.5,56,'kusuma',True]
print(list1+l2)
#list1.extend(l2)
#print(list1)

[10, 'ant', 23.5, 'inserted', 'K', 'appended', 'appended', 4.5, 56, 'kusuma', True, 4.5, 56, 'kusuma', True]
[10, 'ant', 23.5, 'inserted', 'K', 'appended', 'appended', 4.5, 56, 'kusuma', True, 4.5, 56, 'kusuma', True]


In [ ]:
#removing element by giving ele name
list1.remove('kusuma')#list_name.remove(element)
print(list1)

[10, 'ant', 23.5, 'inserted', 'K', 4.5, 56, True, 4.5, 56, True]
[10, 'ant', 23.5, 'inserted', 'K', 4.5, 56, True, 56, True]


In [ ]:
#removing ele using index
list1.pop(8)#list_name.pop(index)
print(list1)

In [ ]:
#clearing all elements in a list
list1.clear()
print(list1)

[]


In [ ]:
#create list of random integers 0f 10 elements print their squares save this squares in a new list
l1=[4,76,43,12,33,3,11,23,67,99]
l2=[]
for i in l1:
  l2.append(i*i)
print(l2)


[16, 5776, 1849, 144, 1089, 9, 121, 529, 4489, 9801]


In [ ]:
#list comprehension
#newlist=[output for]
lst1=[4,76,43,12,33,3,11,23,67,99]
res=[i*i for i in lst1]
print(res)

[16, 5776, 1849, 144, 1089, 9, 121, 529, 4489, 9801]


In [ ]:
res=[i*i for i in lst1 if i>50]#newlist=[output for if]
print(res)

NameError: name 'lst1' is not defined

In [ ]:
#newlist=[(st of if) if (cond) else (st if else) for]
l1=[23,67,12,34,69]
res=[i*i if i>50 else 'X' for i in l1]
print(res)

['X', 4489, 'X', 'X', 4761]


In [ ]:
#take the salary from tthe user if the salary is less tthan 50k then 10% tax otherwise 15%
sal=int(input("enter salary:"))
sl=[(sal-(sal*10/100)) if sal<50000 else sal-(sal*15/100) ]
print(sl)





enter salary:67000
[56950.0]


In [ ]:
sall=[50000,56000,39000,45000]
salres=[(i-(i*10/100)) if i<50000 else i-(i*15/100) for i in l]
print(salres)

NameError: name 'l' is not defined

Dicionary:

dictname={key1:val1,key2:val2,......}

In [ ]:
#create
dict={'mentor':'jwalitha','l0':'kusuma','p3':'rupa',11:'mahi'}
print(dict)

{'mentor': 'jwalitha', 'l0': 'kusuma', 'p3': 'rupa', 11: 'mahi'}


In [ ]:
dict1={'mentor':'jwalitha','mentor':'kusuma','p3':'rupa',11:'mahi'}
print(dict1)

{'mentor': 'kusuma', 'p3': 'rupa', 11: 'mahi'}


In [ ]:
print(dict.values()) #printing values
print(dict.keys()) #printing keys

dict_values(['jwalitha', 'kusuma', 'rupa', 'mahi'])
dict_keys(['mentor', 'l0', 'p3', 11])


In [ ]:
print(dict['mentor'])

jwalitha


In [ ]:
dict2={'dept':'cse','details':{'year':'II','sec':'D','count':71}}
print(dict2['details']['sec'])

D


In [ ]:
print("year is ",dict2['details']['year'])
print("section is ",dict2['details']['sec'])
print("total is ",dict2['details']['count'])

year is  II
section is  D
total is  71


In [ ]:
#create a dictionary from two lists
idl=[34,56,78,39,100]
names=["joe","suji","rohini","shankar","mani"]
z=zip(idl,names)
for i in z:
  print(i)

(34, 'joe')
(56, 'suji')
(78, 'rohini')
(39, 'shankar')
(100, 'mani')


In [ ]:
idl=[34,56,78,39,100]
names=["joe","suji","rohini","shankar","mani"]
newdict=dict(zip(idl,names))
print(newdict)

{34: 'joe', 56: 'suji', 78: 'rohini', 39: 'shankar', 100: 'mani'}


NUMPY

In [ ]:
import numpy as np
A=np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
import numpy as np
A2=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2d array
#elements in each row =columns
print(A2)
print(A2.ndim)
print(A2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [ ]:
A3=np.array([[[1,2,4],[6,3,4]],[[3,5,6],[10,8,9]]]) #3d array
#no of elements=no of arrays*no of rows*no.of columns
print(A3)
print(A3.ndim)
print(A3.shape)

[[[ 1  2  4]
  [ 6  3  4]]

 [[ 3  5  6]
  [10  8  9]]]
3
(2, 2, 3)


In [ ]:
A11=np.ones((2,4,3)) #g,r,c
print(A11)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
A12=np.zeros((2,4,3)) #g,r,c
print(A12)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#identity matrix
A13=np.eye(4)
print(A13)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A14=np.arange(1,10)#start,stop,step
print(A14)
print(type(A14))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using a range function between 1 and 1000
a15=np.arange(8,1001,8)
print(a15)
print(type(a15))


[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
#linspace-spliting a range into n numbers with common differences
a16=np.linspace(18,16,17) #l,u,n
print(a16)
a17=np.linspace(15,16,17)
print(a17)

[18.    17.875 17.75  17.625 17.5   17.375 17.25  17.125 17.    16.875
 16.75  16.625 16.5   16.375 16.25  16.125 16.   ]
[15.     15.0625 15.125  15.1875 15.25   15.3125 15.375  15.4375 15.5
 15.5625 15.625  15.6875 15.75   15.8125 15.875  15.9375 16.    ]


TUPLES

tuples,sets,documentation,qr code

In [5]:

#creating a tuple
tup=() #empty tuple
tup1=(1,2,3,4,5) #tuple with integers
tup2=('c','a','k')
tup3=(3,4.5,'k','abc')
print(tup1)
print(tup2)
print(tup3)

(1, 2, 3, 4, 5)
('c', 'a', 'k')
(3, 4.5, 'k', 'abc')


In [6]:
#type
print(type(tup1))

<class 'tuple'>


In [7]:
# 2 tuples as single tuple
tup1=(1,2,3,4,5)
tup4=(56,7,8,3,3)
print(tup1+tup4)

(1, 2, 3, 4, 5, 56, 7, 8, 3, 3)


In [8]:
#we cannot delete values from tuple
del tup1[2]
print(tup1)

TypeError: 'tuple' object doesn't support item deletion

In [9]:
#index method
tup1=(1,2,3,4,5)
print(tup1.index(2)) #tuple.index(ele)

1


In [14]:
#count method-returns a no.of elements in a specific value
tup5=("kusuma")
print("the count of tuple is",tup5.count('u'))

the count of tuple is 2


In [15]:
#tuple assignement
(v1,v2,v3)=(34,4.5,6)
print(v1,v2,v3)

34 4.5 6


In [17]:
#nested tuples
stup=(("kusuma",'cse'),("mahi",'ai'),("rupa",'cse'))
for i in stup:
  print(i)

('kusuma', 'cse')
('mahi', 'ai')
('rupa', 'cse')


In [18]:

tup1=(1,2,3,4,5)
for i in tup1:
  print(i)

1
2
3
4
5


In [19]:
stup=(("kusuma",'cse'),("mahi",'ai'),("rupa",'cse'))
for val in stup:
  for i in val:
    print(i)

kusuma
cse
mahi
ai
rupa
cse


SETS

In [20]:
#sets are unordered, unindexed, mo duplicates are not allowed
s={21,45.5,"sets",'S',123}
print(s)

{'S', 21, 'sets', 123, 45.5}
